# -*- coding: utf-8 -*-
"""
Created on Mon Sep 05 16:41:54 2016

@author: Hunter


Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

start = 40755

triangles = []
pentagonals = []
hexagonals = []

def compute():
    for n in range(20000,100000):
        tri = (n * (n+1)) / 2
        triangles.append(tri)
    for n in range(20000,100000):
        pen = (n * (3*n - 1))/2
        pentagonals.append(pen)
    for n in range(20000,100000):
        hexx = (n * (2*n -1))
        hexagonals.append(hexx)
    for x in triangles:
        if x in triangles and x in pentagonals and x in hexagonals:
            print(x)

        
        
        
    
